# Generated by Django 6.0.4 on 2026-05-01 08:13

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0012_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='availabilityexception',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commissionrule',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disputeevidence',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payout',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='providerearnings',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
    ]
