# Generated by Django 6.0.4 on 2026-05-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_booking_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
