"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k4)xzmg_@lc9ro5b5)6jy^&-iz29&v+_p4hzq*d(&q9kw7yn-_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "apps.core",
]

# Unfold theme settings
UNFOLD = {
    "SITE_TITLE": "Kyusa Admin",
    "SITE_HEADER": "Kyusa Service Marketplace",
    "SITE_URL": "/",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "STYLES": [
        lambda request: "/static/css/admin-override.css",
    ],
    "COLORS": {
        "primary": {
            "50": "240 253 244",
            "100": "220 252 231",
            "200": "187 247 208",
            "300": "134 239 172",
            "400": "74 222 128",
            "500": "34 197 94",
            "600": "22 163 74",
            "700": "21 128 61",
            "800": "22 101 52",
            "900": "20 83 45",
            "950": "5 46 22",
        },
    },
    "TABS": [
        {
            "models": [
                "core.user",
                "core.role",
            ],
            "items": [
                {
                    "title": "Users",
                    "link": "/admin/core/user/",
                },
                {
                    "title": "Roles",
                    "link": "/admin/core/role/",
                },
            ],
        },
    ],
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "User Management",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": "/admin/core/user/",
                    },
                    {
                        "title": "Roles",
                        "icon": "group",
                        "link": "/admin/core/role/",
                    },
                ],
            },
            {
                "title": "Service Marketplace",
                "separator": True,
                "items": [
                    {
                        "title": "Departments",
                        "icon": "business",
                        "link": "/admin/core/department/",
                    },
                    {
                        "title": "Categories",
                        "icon": "category",
                        "link": "/admin/core/servicecategory/",
                    },
                    {
                        "title": "Services",
                        "icon": "medical_services",
                        "link": "/admin/core/service/",
                    },
                ],
            },
            {
                "title": "Profiles",
                "separator": True,
                "items": [
                    {
                        "title": "Providers",
                        "icon": "store",
                        "link": "/admin/core/providerprofile/",
                    },
                    {
                        "title": "Clients",
                        "icon": "account_circle",
                        "link": "/admin/core/clientprofile/",
                    },
                ],
            },
            {
                "title": "Operations",
                "separator": True,
                "items": [
                    {
                        "title": "Bookings",
                        "icon": "event",
                        "link": "/admin/core/booking/",
                    },
                    {
                        "title": "Reviews",
                        "icon": "star",
                        "link": "/admin/core/review/",
                    },
                    {
                        "title": "Disputes",
                        "icon": "gavel",
                        "link": "/admin/core/dispute/",
                    },
                ],
            },
            {
                "title": "Financials",
                "separator": True,
                "items": [
                    {
                        "title": "Transactions",
                        "icon": "payments",
                        "link": "/admin/core/paymenttransaction/",
                    },
                    {
                        "title": "Earnings",
                        "icon": "account_balance_wallet",
                        "link": "/admin/core/providerearnings/",
                    },
                    {
                        "title": "Payouts",
                        "icon": "outbound",
                        "link": "/admin/core/payout/",
                    },
                    {
                        "title": "Commission Rules",
                        "icon": "percent",
                        "link": "/admin/core/commissionrule/",
                    },
                ],
            },
            {
                "title": "System",
                "separator": True,
                "items": [
                    {
                        "title": "Settings",
                        "icon": "settings",
                        "link": "/admin/core/systemsetting/",
                    },
                    {
                        "title": "Audit Logs",
                        "icon": "history",
                        "link": "/admin/core/auditlog/",
                    },
                    {
                        "title": "Notifications",
                        "icon": "notifications",
                        "link": "/admin/core/notification/",
                    },
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
AUTH_USER_MODEL = 'core.User'

# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('SMTP_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('SMTP_PORT', 465))
EMAIL_USE_SSL = True
EMAIL_HOST_USER = os.getenv('SMTP_USER')
EMAIL_HOST_PASSWORD = os.getenv('SMTP_PASS')
DEFAULT_FROM_EMAIL = os.getenv('SMTP_FROM', 'noreply@kyusa.com')